#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

#  cookbook 'chef-client', '>= 10.20.0'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
  cookbook 'apt'
  cookbook 'nginx'
  cookbook 'percona',
    :git => 'https://github.com/phlipper/chef-percona.git'
  cookbook 'php'
  cookbook 'php-fpm'
  cookbook 'database'
